// lib/carMakes.ts
export const carMakesData = [
  { value: "acura", label: "Acura", country: "Japan" },
  { value: "alfa-romeo", label: "Alfa Romeo", country: "Italy" },
  { value: "aston-martin", label: "Aston Martin", country: "UK" },
  { value: "audi", label: "Audi", country: "Germany" },
  { value: "bentley", label: "Bentley", country: "UK" },
  { value: "bmw", label: "BMW", country: "Germany" },
  { value: "buick", label: "Buick", country: "USA" },
  { value: "cadillac", label: "Cadillac", country: "USA" },
  { value: "chevrolet", label: "Chevrolet", country: "USA" },
  { value: "chrysler", label: "Chrysler", country: "USA" },
  { value: "dodge", label: "Dodge", country: "USA" },
  { value: "ferrari", label: "Ferrari", country: "Italy" },
  { value: "fiat", label: "Fiat", country: "Italy" },
  { value: "ford", label: "Ford", country: "USA" },
  { value: "genesis", label: "Genesis", country: "South Korea" },
  { value: "gmc", label: "GMC", country: "USA" },
  { value: "honda", label: "Honda", country: "Japan" },
  { value: "hyundai", label: "Hyundai", country: "South Korea" },
  { value: "infiniti", label: "Infiniti", country: "Japan" },
  { value: "jaguar", label: "Jaguar", country: "UK" },
  { value: "jeep", label: "Jeep", country: "USA" },
  { value: "kia", label: "Kia", country: "South Korea" },
  { value: "lamborghini", label: "Lamborghini", country: "Italy" },
  { value: "land-rover", label: "Land Rover", country: "UK" },
  { value: "lexus", label: "Lexus", country: "Japan" },
  { value: "lincoln", label: "Lincoln", country: "USA" },
  { value: "maserati", label: "Maserati", country: "Italy" },
  { value: "mazda", label: "Mazda", country: "Japan" },
  { value: "mclaren", label: "McLaren", country: "UK" },
  { value: "mercedes-benz", label: "Mercedes-Benz", country: "Germany" },
  { value: "mini", label: "Mini", country: "UK" },
  { value: "mitsubishi", label: "Mitsubishi", country: "Japan" },
  { value: "nissan", label: "Nissan", country: "Japan" },
  { value: "polestar", label: "Polestar", country: "Sweden" },
  { value: "porsche", label: "Porsche", country: "Germany" },
  { value: "ram", label: "Ram", country: "USA" },
  { value: "rivian", label: "Rivian", country: "USA" },
  { value: "rolls-royce", label: "Rolls-Royce", country: "UK" },
  { value: "subaru", label: "Subaru", country: "Japan" },
  { value: "tesla", label: "Tesla", country: "USA" },
  { value: "toyota", label: "Toyota", country: "Japan" },
  { value: "volkswagen", label: "Volkswagen", country: "Germany" },
  { value: "volvo", label: "Volvo", country: "Sweden" },
];

export type CarMakeData = typeof carMakesData[number];